config/routes.rb
Rails.application.routes.draw do
  resources :messages
  resources :areas, except: [:create, :destroy] do
    collection do
      get :overview
      get :open
      get :closed
    end
  end

  get '/status', to: 'status#index'
  get '/docs', to: 'doc#index'
  root :to => 'welcome#index'

  get '/logout', to: 'sessions#destroy'
  get '/login', to: 'sessions#new'
  get '/auth/:provider/disable', to: 'users#disable_provider'
  post '/auth/:provider/callback', to: 'sessions#create'
  get '/auth/:provider/callback', to: 'sessions#create'
  get '/auth/failure', to: 'sessions#failure'
  resources :sessions
  resources :memberships

  resources :users

  namespace :admin do
    resources :users
    # resources :areas
  end
end

app/models/area.rb
class Area < ActiveRecord::Base
  extend FriendlyId
  friendly_id :name, use: :slugged

  has_many :areas_messages
  has_many :messages, through: :areas_messages

  has_many :snow_messages, -> {snow}, through: :areas_messages, source: :message
  has_many :soil_messages, -> {soil}, through: :areas_messages, source: :message
  has_many :alert_messages, -> {alert}, through: :areas_messages, source: :message
  has_many :operational_messages, -> {operational}, through: :areas_messages, source: :message

  after_commit :regenerate_overview_image, on: :update

  TravelStatus = %w{Open Closed}.map{|s| [s, s]}

  %w{snow_message_id soil_message_id }.each do |field|
    define_method("#{field}=".to_sym) do |id|  # def snow_message_id=(id)
      self.send("#{field}s=".to_sym, id)       #   self.send(:snow_message_ids=, id)
    end                                        # end
    define_method(field) do                    # def snow_message_id
      self.send("#{field}s".to_sym).first      #   self.send(:snow_message_ids).first
    end                                        # end
    define_method(field.chomp("_id")) do       # def snow_message
      self.send("#{field}s".to_sym).first      #   self.send(:snow_messages).first
    end                                        # end
  end

  def geometry
    GeoRuby::SimpleFeatures::Geometry.from_ewkt(geom)
  end

  private
  def regenerate_overview_image
    ImageCacheJob.perform_later('overview')
  end
end

app/controllers/areas_controller.rb
class AreasController < ApplicationController
  before_action :set_area, only: [:show, :edit, :update, :destroy]
  authorize_resource
  skip_authorize_resource :only => :overview

  # GET /areas
  # GET /areas.json
  def index
    @areas = Area.all
  end

  # GET /areas/1
  # GET /areas/1.json
  def show
  end

  # GET /areas/1/edit
  def edit
  end

  def overview
    @image = Image.where(name: 'overview', size: (params[:size] || 'medium')).first
    respond_to do |format|
      format.png do
        send_data Base64.decode64(@image.try(:data)), type: :png, disposition: 'inline'
      end
      format.jpg do
        send_data Base64.decode64(@image.try(:data)), type: :jpg, disposition: 'inline'
      end
    end
  end

  # PATCH/PUT /areas/1
  # PATCH/PUT /areas/1.json
  def update
    respond_to do |format|
      if @area.update(area_params)
        format.html { redirect_to @area, notice: 'Area was successfully updated.' }
        format.json { render :show, status: :ok, location: @area }
      else
        format.html { render :edit }
        format.json { render json: @area.errors, status: :unprocessable_entity }
      end
    end
  end

  def open
    @areas = Area.where(travel_status: 'Open')
    respond_to do |format|
      format.geojson
    end
  end

  def closed
    @areas = Area.where(travel_status: 'Closed')
    respond_to do |format|
      format.geojson
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_area
      @area = Area.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def area_params
      params.require(:area).permit(:name, :travel_status, :geom, :notes, :order, :as_of, :message_ids,
        :snow_message_id, :soil_message_id, :alert_message_ids => [], :operational_message_ids => [])
    end

end

app/helpers/areas_helper.rb
module AreasHelper
  def area_content_id(area)
    "#area-#{area.name.parameterize}-content"
  end

  def area_heading_id(area)
    "#area-#{area.name.parameterize}"
  end

  def area_class(area)
    case area.travel_status.downcase
    when 'open'
      'list-group-item-success'
    when 'closed'
      'list-group-item-danger'
    else
      'list-group-item-default'
    end
  end
end

app/views/areas/_alert.html+mobile.haml
.list-group-item.list-group-item-default
  = alert.mobile_text

app/views/areas/_alert.html.haml
= alert.full_text
%br

app/views/areas/_area.html.haml
.panel.panel-default.area-panel
  .panel-heading
    %h1.panel-title
      = link_to area.name, area_path(area)
      %small
        Updated #{time_ago_in_words area.updated_at} ago
    = render 'areas/ribbon', area: area
  .panel-body
    %dl
      %dt Travel Status
      %dd= area.travel_status
      %dt Effective
      %dd= area.as_of || area.updated_at.to_date
      - if area.soil_messages.any?
        %dt Soil Temperature
        %dd= area.soil_messages.first.try(:full_text)
      - if area.snow_messages.any?
        %dt Snow Status
        %dd= area.snow_messages.first.try(:full_text)

      - unless area.alert_messages.empty?
        %dt Alerts
        %dd
          = render partial: 'alert', collection: area.alert_messages
      - unless area.operational_messages.empty?
        %dt Operational Considerations
        %dd
          = render partial: 'alert', collection: area.operational_messages
      - unless area.notes.blank?
        %dt Notes
        %dd
          = area.notes

app/views/areas/_form.html.haml
= bootstrap_form_for(@area) do |f|
  .row
    .col-sm-5
      = f.select :travel_status, Area::TravelStatus, label: 'Travel Status:'
    .col-sm-5
      = f.date_field :as_of, label: 'Effective'
    .col-sm-2
      = f.number_field :order, placeholder: 'mm/dd/yyyy'
  .row
    .col-sm-7
      = f.collection_check_boxes :operational_message_ids, Message.operational, :id, :full_text, label: 'Operational Conditions'
      = f.collection_radio_buttons :soil_message_id, Message.soil, :id, :full_text, label: 'Soil Conditions'
    .col-sm-5
      = f.collection_check_boxes :alert_message_ids, Message.alert, :id, :full_text, label: 'Alert Conditions'
      = f.collection_radio_buttons :snow_message_id, Message.snow, :id, :full_text, label: 'Snow Conditions'
  = f.text_area :notes, rows: 5
  = link_to 'Cancel', @area, class: 'btn btn-default'
  = f.submit class: 'btn btn-primary pull-right', data: {target: '#updateAreasModal', toggle: 'modal'}


#updateAreasModal.modal.fade{data: {backdrop: 'static'}}
  .modal-dialog
    .modal-content
      .modal-header
        %h4 Updating Areas
      .modal-body
        Regenerating overview images, please be patient.
        .progress
          .progress-bar.progress-bar-striped.active{style: "width: 100%"}

app/views/areas/_ribbon.html.haml
.ribbon{ class: "ribbon-#{area.travel_status.downcase}"}= area.travel_status

app/views/areas/edit.html.haml
%h1= @area.name
= render 'form'

app/views/areas/index.html.haml
%h1 Listing areas
%table
  %thead
    %tr
      %th Name
      %th Travel status
      %th Geom
      %th Notes
      %th Order
      %th{:colspan => "3"}
  %tbody
    - @areas.each do |area|
      %tr
        %td= area.name
        %td= area.travel_status
        %td= area.geom
        %td= area.notes
        %td= area.order

app/views/areas/new.html.haml
%h1 New Area
= render 'form'

app/views/areas/show.html.haml
.row
  .col-md-6.col-md-offset-3
    - if can? :manage, @area
      %p
        = link_to edit_area_path(@area), class: 'btn btn-primary btn-block' do
          %i.fa.fa-inverse.fa-edit
          Edit

    = render @area