config/routes.rb
Rails.application.routes.draw do
  resources :messages
  resources :areas, except: [:create, :destroy] do
    collection do
      get :overview
      get :open
      get :closed
    end
  end

  get '/status', to: 'status#index'
  get '/docs', to: 'doc#index'
  root :to => 'welcome#index'

  get '/logout', to: 'sessions#destroy'
  get '/login', to: 'sessions#new'
  get '/auth/:provider/disable', to: 'users#disable_provider'
  post '/auth/:provider/callback', to: 'sessions#create'
  get '/auth/:provider/callback', to: 'sessions#create'
  get '/auth/failure', to: 'sessions#failure'
  resources :sessions
  resources :memberships

  resources :users

  namespace :admin do
    resources :users
    # resources :areas
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new

    if user.admin?
      can :manage, :all
    elsif user.manager?
      can :manage, Area
    else
      can :read, Area
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/area.rb
class Area < ActiveRecord::Base
  extend FriendlyId
  friendly_id :name, use: :slugged

  has_many :areas_messages
  has_many :messages, through: :areas_messages

  has_many :snow_messages, -> {snow}, through: :areas_messages, source: :message
  has_many :soil_messages, -> {soil}, through: :areas_messages, source: :message
  has_many :alert_messages, -> {alert}, through: :areas_messages, source: :message
  has_many :operational_messages, -> {operational}, through: :areas_messages, source: :message

  after_commit :regenerate_overview_image, on: :update

  TravelStatus = %w{Open Closed}.map{|s| [s, s]}

  %w{snow_message_id soil_message_id }.each do |field|
    define_method("#{field}=".to_sym) do |id|  # def snow_message_id=(id)
      self.send("#{field}s=".to_sym, id)       #   self.send(:snow_message_ids=, id)
    end                                        # end
    define_method(field) do                    # def snow_message_id
      self.send("#{field}s".to_sym).first      #   self.send(:snow_message_ids).first
    end                                        # end
    define_method(field.chomp("_id")) do       # def snow_message
      self.send("#{field}s".to_sym).first      #   self.send(:snow_messages).first
    end                                        # end
  end

  def geometry
    GeoRuby::SimpleFeatures::Geometry.from_ewkt(geom)
  end

  private
  def regenerate_overview_image
    ImageCacheJob.perform_later('overview')
  end
end

app/models/areas_message.rb
class AreasMessage < ActiveRecord::Base
  belongs_to :area
  belongs_to :message

end

app/models/authorization.rb
class Authorization < ActiveRecord::Base
  include GinaAuthentication::AuthorizationModel
end

app/models/image.rb
class Image < ActiveRecord::Base
end

app/models/membership.rb
class Membership < ActiveRecord::Base
  include GinaAuthentication::MembershipModel
end

app/models/message.rb
class Message < ActiveRecord::Base
  has_many :areas_messages
  has_many :areas, through: :areas_messages

  scope :alert, -> { where(group: 'alert') }
  scope :operational, -> { where(group: 'operational') }
  scope :snow, -> { where(group: 'snow') }
  scope :soil, -> { where(group: 'soil') }
end

app/models/user.rb
class User < ActiveRecord::Base
  include GinaAuthentication::UserModel

  ROLES = %w{guest manager admin}

  def admin?
    role == 'admin'
  end

  def manager?
    role == 'manager'
  end

end

app/models/zone.rb
class Zone < ActiveRecord::Base
  has_and_belongs_to_many :messages
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  layout 'admin'
end

app/controllers/areas_controller.rb
class AreasController < ApplicationController
  before_action :set_area, only: [:show, :edit, :update, :destroy]
  authorize_resource
  skip_authorize_resource :only => :overview

  # GET /areas
  # GET /areas.json
  def index
    @areas = Area.all
  end

  # GET /areas/1
  # GET /areas/1.json
  def show
  end

  # GET /areas/1/edit
  def edit
  end

  def overview
    @image = Image.where(name: 'overview', size: (params[:size] || 'medium')).first
    respond_to do |format|
      format.png do
        send_data Base64.decode64(@image.try(:data)), type: :png, disposition: 'inline'
      end
      format.jpg do
        send_data Base64.decode64(@image.try(:data)), type: :jpg, disposition: 'inline'
      end
    end
  end

  # PATCH/PUT /areas/1
  # PATCH/PUT /areas/1.json
  def update
    respond_to do |format|
      if @area.update(area_params)
        format.html { redirect_to @area, notice: 'Area was successfully updated.' }
        format.json { render :show, status: :ok, location: @area }
      else
        format.html { render :edit }
        format.json { render json: @area.errors, status: :unprocessable_entity }
      end
    end
  end

  def open
    @areas = Area.where(travel_status: 'Open')
    respond_to do |format|
      format.geojson
    end
  end

  def closed
    @areas = Area.where(travel_status: 'Closed')
    respond_to do |format|
      format.geojson
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_area
      @area = Area.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def area_params
      params.require(:area).permit(:name, :travel_status, :geom, :notes, :order, :as_of, :message_ids,
        :snow_message_id, :soil_message_id, :alert_message_ids => [], :operational_message_ids => [])
    end

end

app/controllers/status_controller.rb
class StatusController < ApplicationController
  def index
    render :index, layout: 'status'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include GinaAuthentication::Users
end

app/helpers/application_helper.rb
module ApplicationHelper
  def image_size
    browser.mobile? ? 'small' : 'medium'
  end

  def bootstrap_flash_type(type)
    case type
    when 'notice'
      'success'
    when 'error'
      'danger'
    else
      'info'
    end
  end
end

app/helpers/areas_helper.rb
module AreasHelper
  def area_content_id(area)
    "#area-#{area.name.parameterize}-content"
  end

  def area_heading_id(area)
    "#area-#{area.name.parameterize}"
  end

  def area_class(area)
    case area.travel_status.downcase
    when 'open'
      'list-group-item-success'
    when 'closed'
      'list-group-item-danger'
    else
      'list-group-item-default'
    end
  end
end

app/helpers/memberships_helper.rb
module MembershipsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper

  def role_help
    [
      [ "Guest", "Has no special priviledges." ],
      [ "Manager", "Can update areas." ],
      [ "Admin", "Has Manager priviledges and can modify users permissions" ]
    ]
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
  def show_map_image(size)
    link_to_unless browser.mobile?, map_image_tag(size), map_image_url, target: :_blank
  end

  def map_image_tag(size = 'large')
    image_tag(map_image_url(size), alt: "Tundra Area Travel Status")
  end

  def map_image_url(image_size = 'large')
    "#{areas_path}/overview.jpg?size=#{image_size}"
  end
end

app/views/layouts/_analytics.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-6824535-20', 'auto');
  ga('send', 'pageview');
</script>

app/views/layouts/_flash_messages.html.haml
- flash.each do |type,msg|
  .alert{ class: "alert-#{bootstrap_flash_type(type)}" }
    %button.close{ data: { dismiss: 'alert' }} &times;
    = msg

app/views/layouts/_footer.html.haml
.footer
  .logo
    = link_to image_tag("UAFLogo_A_647-small.png"), 'http://www.uaf.edu'
  .logo
    = link_to image_tag("akdnr-logo.png"), 'http://dnr.alaska.gov'
  .logo
    = link_to image_tag("gina-logo2.png"), 'http://gina.alaska.edu'

app/views/layouts/_login.html.haml
- if signed_in?
  = link_to "Logout", logout_path
- else
  = link_to '#', class: 'dropdown-toggle', data: {toggle: 'dropdown'} do
    Login
    %span.caret
  %ul.dropdown-menu
    %li
      = link_to '/auth/google', class: 'navbar-link' do
        %i.fa.fa-fw.fa-2x.fa-google-plus-square
        Google
    %li
      = link_to '/auth/gina', class: 'navbar-link' do
        %i.fa.fa-fw.fa-2x.fa-google-plus-square
        GinaID

app/views/layouts/_navbar.html.haml
.navbar.navbar-default.navbar-static-top
  .container-fluid
    .navbar-header
      =link_to "TTN Travel Status", root_url, class: 'navbar-brand'
      %button.navbar-toggle.collapsed{data: {toggle: 'collapse', target: '#navbar-menu'}}
        %span.sr-only 'Toggle Nav'
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar

    #navbar-menu.collapse.navbar-collapse
      %ul.nav.navbar-nav.navbar-right
        - if current_user.admin?
          %li= link_to "Admin", admin_users_path
        %li= mail_to 'support+ttn@gina.alaska.edu', "Contact Us"
        %li= link_to "About", page_path(:about)
        %li= render 'layouts/login'

app/views/layouts/admin.html.haml
!!!
%html
  %head
    %title Tundra Travel Network Manager
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = render 'layouts/navbar'

    .container.content
      .row
        .flash
          = render 'layouts/flash_messages'
      .row
        .col-md-2
          .list-group
            = link_to "Users", admin_users_path, class: 'list-group-item active'
        .col-md-10
          = yield

app/views/layouts/application.html+mobile.haml
!!!
%html
  %head
    %title Tundra Travel Network Manager
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    %meta{name: 'viewport', content:"width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" }
  %body
    = render 'layouts/analytics'
    = render 'layouts/navbar'

    .container-fluid
      .flash
        = render 'layouts/flash_messages'
      = yield
    = render 'layouts/footer'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Tundra Travel Network Manager
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = render 'layouts/analytics'
    = render 'layouts/navbar'
    .container-fluid
      .flash
        = render 'layouts/flash_messages'
      .content= yield
      = render 'layouts/footer'

app/views/layouts/status.html.haml
!!!
%html
  %head
    %title Tundra Travel Network Manager
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    %meta{name: 'viewport', content:"width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" }
  %body
    = yield

app/views/pages/about.html.haml
.container
  %p
    The Northern Regional Office (NRO) within the Alaska Department of Natural Resources, Division of
    Mining, Land, and Water (DNR/DMLW) is responsible for managing off-road travel on State land
    within the North Slope of Alaska. In 2010, the NRO worked with the Geographic Information
    Network of Alaska (GINA), as part of the Arctic Transportation Network project, to develop a
    mobile application, spatial database, web map service, and website to support the management and
    distribution of tundra travel information to industry, agencies, and the public. With the sunset of
    that project, the DNR/DMLW and GINA began a new effort at the end of 2014 to upgrade the project
    components. This webpage is the result and allows quick access to tundra (off-road) travel conditions on the North Slope.

  %p
    The NRO actively monitors snow depth and soil temperatures throughout the winter season to
    determine when to open the tundra to general off-road travel. Monitoring stations are located
    within four tundra opening areas: the Western Coastal, the Eastern Coastal, and the Upper Foothills
    and the Lower Foothills of the Brooks Range. The tundra is opened to off-road travel in the Coastal
    areas when the soil temperature at a depth of twelve inches reaches -5˚C and when there is six (6)
    inches of snow on the ground. In the Foothills areas, tundra opening occurs when the soil
    temperature reaches -5˚C and when there is nine (9) inches of snow on the ground. The date of
    tundra opening has ranged from as early as November 4 to as late as January 27. Once the tundra
    has been opened in the winter, there are no restrictions on the type of vehicles that may operate on
    the tundra, on condition that all other terms and stipulations under a permit, obtained as required
    per the North Slope Special Use Lands designation (ADL 50666), are followed. In years of limited
    snowfall, the tundra may be opened conditionally with specific operating restrictions.

  %p
    The tundra is closed when it appears that thawing conditions have resulted in degraded snow pack
    that has lost the structural capacity to support vehicles and may result in damage to the tundra.
    Since data collection began in 1969/1970, the date of tundra closure has ranged from April 21 to
    June 4. In order to avoid significant damage to the tundra environment, no off-road travel except for
    emergency situations is permitted for the period from break-up until July 15 due to saturated soil
    conditions and migratory bird nesting. Permitted summer tundra travel may begin on July 15 and is
    limited to vehicles that have been tested and approved by the DNR/DMLW. The purpose of vehicle
    testing is to determine which vehicles can operate on the tundra during the summer without
    causing damage to the tundra.

  %p
    This webpage is updated by members of the Northern Region Oil & Gas Team who conduct almost
    weekly field inspections throughout the winter and spring seasons. If you have any questions,
    please contact the NRO at 907-451-2740 for more information.